leela_zero_pytorch: leela-zero-pytorch

---

!Experiment

resources:
  train_dir: data/train-sm
  val_dir: data/val-sm
  test_dir: data/test-sm

name: leela-zero-pytorch-train-sm

pipeline:

  dataset: !leela_zero_pytorch.GoDataset.from_data_dir
    train_dir: !@ train_dir
    val_dir: !@ val_dir
    test_dir: !@ test_dir

  model: !leela_zero_pytorch.Network
    board_size: 19
    in_channels: 18
    residual_channels: 32
    residual_layers: 8

  train: !leela_zero_pytorch.GoTrainer
    dataset: !@ dataset
    model: !@ model
    train_sampler: !BaseSampler
      batch_size: 16
    val_sampler: !@ train[train_sampler]
    loss_fn: !leela_zero_pytorch.MSECrossEntropyLoss
      alpha: 0.01
    metric_fn: !@ train[loss_fn]
    optimizer: !torch.Adam
      params: !@ train[model].trainable_params
    lower_is_better: true
    max_steps: 100

  eval: !leela_zero_pytorch.GoEvaluator
    dataset: !@ dataset
    model: !@ train.model
    metric_fn: !@ train[loss_fn]
    eval_sampler: !@ train[train_sampler]
