leela_zero_pytorch: leela-zero-pytorch

---

!Experiment

resources:
  train_dir: data/train
  val_dir: data/val
  test_dir: data/test

name: leela-zero-pytorch-train-huge

pipeline:

  train: !leela_zero_pytorch.GoTrainer
    dataset: !leela_zero_pytorch.GoDataset.from_data_dir
      train_dir: !@ train_dir
      val_dir: !@ val_dir
      test_dir: !@ test_dir
    model: !leela_zero_pytorch.Network
      board_size: 19
      in_channels: 18
      residual_channels: 256
      residual_layers: 40
    train_sampler: !BaseSampler
      batch_size: 1024
      n_workers: 64
    val_sampler: !@ train[train_sampler]
    loss_fn: !leela_zero_pytorch.MSECrossEntropyLoss
      alpha: 1
    metric_fn: !@ train[loss_fn]
    optimizer: !torch.Adam
      params: !@ train[model].trainable_params
      weight_decay: 0.0001
    lower_is_better: true
    max_steps: 100
