!Environment

extensions:
  leela_zero_pytorch: leela-zero-pytorch

local_files:
  train_dir: data/train-sm
  val_dir: data/val-sm
  test_dir: data/test-sm

---

!Pipeline

name: leela-zero-pytorch-train-sm

pipeline:

  train: !leela_zero_pytorch.GoTrainer
    dataset: !leela_zero_pytorch.GoDataset.from_data_dir
      train_dir: !file train_dir
      val_dir: !file val_dir
      test_dir: !file test_dir
    model: !leela_zero_pytorch.Network
      board_size: 19
      in_channels: 18
      residual_channels: 32
      residual_layers: 8
    train_sampler: !BaseSampler
      batch_size: 16
    val_sampler: !ref train[train_sampler]
    loss_fn: !leela_zero_pytorch.MSECrossEntropyLoss
      alpha: 1
    metric_fn: !ref train[loss_fn]
    optimizer: !torch.optim.Adam
      params: !ref train[model].trainable_params
    lower_is_better: true
    max_steps: 100

  eval: !leela_zero_pytorch.GoEvaluator
    dataset: !copy train[dataset]
    model: !copy train.model
    metric_fn: !copy train[loss_fn]
    eval_sampler: !copy train[train_sampler]

gpus_per_trial:
  train: 1
  eval: 1
